import { chmodSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import type { DatabaseSync } from "node:sqlite";
import { PostgresEngine, SqliteEngine, type Dialect, type Params, type PgDriver, type Queries, type Tx } from "./sql.js";

/** Column types that differ between the engines: ids are identity columns, epoch seconds need 64 bits on Postgres. */
interface Types {
  id: string;
  int: string;
}
const TYPES: Record<Dialect, Types> = {
  sqlite: { id: "integer primary key autoincrement", int: "integer" },
  postgres: { id: "bigint generated by default as identity primary key", int: "bigint" },
};

const SCHEMA = (t: Types): string => `
create table users (
  id ${t.id},
  dir_id text not null unique,
  email text,
  display_name text not null,
  avatar_url text,
  created_at ${t.int} not null
);
create table identities (
  id ${t.id},
  user_id ${t.int} not null references users(id) on delete cascade,
  provider text not null,
  provider_user_id text not null,
  email text,
  password_hash text,
  email_verified_at ${t.int},
  created_at ${t.int} not null,
  updated_at ${t.int} not null,
  unique (provider, provider_user_id)
);
create index identities_user on identities(user_id);
create unique index identities_email on identities(lower(email)) where provider = 'email';
create table email_verification_tokens (
  id ${t.id},
  user_id ${t.int} not null references users(id) on delete cascade,
  token_hash text not null unique,
  expires_at ${t.int} not null,
  used_at ${t.int},
  created_at ${t.int} not null
);
create index email_verification_user on email_verification_tokens(user_id);
create table password_reset_tokens (
  id ${t.id},
  user_id ${t.int} not null references users(id) on delete cascade,
  token_hash text not null unique,
  expires_at ${t.int} not null,
  used_at ${t.int},
  created_at ${t.int} not null
);
create index password_reset_user on password_reset_tokens(user_id);
create table sessions (
  id_hash text primary key,
  user_id ${t.int} not null references users(id) on delete cascade,
  created_at ${t.int} not null,
  expires_at ${t.int} not null,
  last_seen_at ${t.int} not null
);
create index sessions_user on sessions(user_id);
create index sessions_expires on sessions(expires_at);
create table oauth_states (
  state_hash text primary key,
  nonce_hash text not null,
  code_verifier text not null,
  expires_at ${t.int} not null
);
create table usage (
  user_id ${t.int} not null references users(id) on delete cascade,
  day text not null,
  llm_rows integer not null default 0,
  primary key (user_id, day)
);
`;

/** Each step brings a database from version i+1 to i+2; a new database runs SCHEMA and then every step. */
const MIGRATIONS: ((t: Types) => string)[] = [
  // 2: per-user API keys for the hosted MCP endpoint. Only a hash of each key is kept.
  (t) => `create table api_keys (
    id ${t.id},
    user_id ${t.int} not null references users(id) on delete cascade,
    name text not null,
    key_hash text not null unique,
    prefix text not null,
    created_at ${t.int} not null,
    last_used_at ${t.int}
  );
  create index api_keys_user on api_keys(user_id);`,
];

const VERSION = 1 + MIGRATIONS.length;

/**
 * The account database, on SQLite (a file under the data folder; one server) or Postgres (one or several servers).
 * Stores call `all`/`one`/`run` for single statements and `transaction` for several that belong together; see sql.ts
 * for how each engine keeps those safe under concurrency.
 */
export class AccountsDb implements Queries {
  private constructor(
    private readonly engine: SqliteEngine | PostgresEngine,
    private readonly file?: string,
  ) {}

  get dialect(): Dialect {
    return this.engine.dialect;
  }

  /** The SQLite connection (tests and maintenance only); undefined on Postgres. */
  get sqlite(): DatabaseSync | undefined {
    return this.engine instanceof SqliteEngine ? this.engine.raw : undefined;
  }

  /** Open (creating if needed) a SQLite file, or ":memory:" for tests. Needs Node 22.13+. */
  static async open(file: string): Promise<AccountsDb> {
    let sqlite: typeof import("node:sqlite");
    try {
      sqlite = await import("node:sqlite");
    } catch {
      throw new Error("Accounts need Node 22.13 or newer (built-in node:sqlite)");
    }
    if (file !== ":memory:") mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
    const raw = new sqlite.DatabaseSync(file);
    raw.exec("pragma journal_mode = wal; pragma foreign_keys = on; pragma busy_timeout = 5000; pragma synchronous = normal;");
    const { user_version } = raw.prepare("pragma user_version").get() as { user_version: number };
    if (user_version < VERSION) {
      raw.exec("begin");
      try {
        if (user_version === 0) raw.exec(SCHEMA(TYPES.sqlite));
        for (const step of MIGRATIONS.slice(Math.max(0, user_version - 1))) raw.exec(step(TYPES.sqlite));
        raw.exec(`pragma user_version = ${VERSION}`);
        raw.exec("commit");
      } catch (e) {
        raw.exec("rollback");
        throw e;
      }
    } else if (user_version !== VERSION) {
      raw.close();
      throw newerSchema(user_version);
    }
    const accounts = new AccountsDb(new SqliteEngine(raw), file);
    accounts.secure();
    return accounts;
  }

  /**
   * Use a Postgres database through `driver` (`pgPoolDriver(url)` in production). The schema is created or upgraded
   * under an advisory lock, so servers starting together migrate once. The version lives in `mockdata_schema`.
   */
  static async openPostgres(driver: PgDriver): Promise<AccountsDb> {
    const engine = new PostgresEngine(driver);
    try {
      await driver.transaction(async (q) => {
        await q.query("select pg_advisory_xact_lock(hashtext('mockdata:schema'))");
        await q.exec("create table if not exists mockdata_schema (version integer not null)");
        const version = Number((await q.query("select version from mockdata_schema")).rows[0]?.version ?? 0);
        if (version > VERSION) throw newerSchema(version);
        if (version === VERSION) return;
        if (version === 0) await q.exec(SCHEMA(TYPES.postgres));
        for (const step of MIGRATIONS.slice(Math.max(0, version - 1))) await q.exec(step(TYPES.postgres));
        await q.query("delete from mockdata_schema");
        await q.query("insert into mockdata_schema (version) values ($1)", [VERSION]);
      });
    } catch (e) {
      await driver.close().catch(() => undefined);
      throw e;
    }
    return new AccountsDb(engine);
  }

  /**
   * A consistent copy of a live SQLite file (WAL included) at `target`, made with VACUUM INTO over a read-only
   * connection, so it is safe while a server is writing and never migrates or changes the source. The copy is
   * readable by this user only. Refuses an existing target.
   */
  static async backupFile(source: string, target: string): Promise<void> {
    if (!existsSync(source)) throw new Error("No account database at that path");
    if (existsSync(target)) throw new Error("The backup file already exists; choose a new name");
    const sqlite = await import("node:sqlite");
    const raw = new sqlite.DatabaseSync(source, { readOnly: true });
    try {
      raw.exec("pragma busy_timeout = 5000");
      raw.prepare("vacuum into ?").run(target);
    } finally {
      raw.close();
    }
    chmodSync(target, 0o600);
  }

  /**
   * Keep a SQLite database (password hashes, emails), its -wal/-shm journal files and its folder readable by this user
   * only, even when the folder already existed with looser permissions. Call again after the first write, when the
   * journal files appear. Nothing to do on Postgres.
   */
  secure(): void {
    if (!this.file || this.file === ":memory:") return;
    chmodSync(path.dirname(this.file), 0o700);
    for (const suffix of ["", "-wal", "-shm"]) if (existsSync(this.file + suffix)) chmodSync(this.file + suffix, 0o600);
  }

  all<T>(sql: string, params?: Params): Promise<T[]> {
    return this.engine.all<T>(sql, params);
  }
  one<T>(sql: string, params?: Params): Promise<T | undefined> {
    return this.engine.one<T>(sql, params);
  }
  run(sql: string, params?: Params): Promise<number> {
    return this.engine.run(sql, params);
  }
  /** Statements that succeed or fail together; take `tx.lock(name)` first for a check-then-write step. */
  transaction<T>(fn: (tx: Tx) => Promise<T>): Promise<T> {
    return this.engine.transaction(fn);
  }

  close(): Promise<void> {
    return this.engine.close();
  }
}

function newerSchema(version: number): Error {
  return new Error(`The account database was made by a newer mockdata (schema ${version}, this build knows ${VERSION})`);
}
